name: Deploy to Unikraft Cloud

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Unikraft CLI
        uses: unikraft/setup-action@v1
        with:
          token: ${{ secrets.UKC_TOKEN }}

      - name: Build and Deploy to Unikraft Cloud
        env:
          UKC_METRO: fra
        run: |
          unikraft build . --output bigboss/web-ssh:latest
          unikraft run \
            --metro fra \
            --publish 443:3000/http+tls \
            --memory 1024M \
            --name web-ssh-console \
            --env APP_ENV=development \
            --env PORT=3000 \
            --env NODE_PATH=/node_modules:/app/node_modules \
            --image bigboss/web-ssh:latest
